INSERT INTO geomaps_area (id, area) VALUES (1,'Agropecuaria');
INSERT INTO geomaps_area (id, area) VALUES (2,'Industrial');
INSERT INTO geomaps_area (id, area) VALUES (3,'Artes');
INSERT INTO geomaps_area (id, area) VALUES (4,'Turismo');
INSERT INTO geomaps_area (id, area) VALUES (5,'Servicio');
INSERT INTO geomaps_area (id, area) VALUES (6,'Comercial');
INSERT INTO geomaps_area (id, area) VALUES (7,'Deportes');
INSERT INTO geomaps_area (id, area) VALUES (8,'Salud');

INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (1,'Apicultura');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (1,'Avicultura');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (1,'Bovinocultura');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (1,'Cavicultura');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (1,'Cunicultura');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (1,'Floricultura');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (1,'Fruticultura');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (1,'Horticultura');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (1,'Lombricultura');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (1,'Ovinocultura');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (1,'Piscicultura');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (1,'Porcinocultura');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (1,'Producción de quinua');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (1,'Viticultura');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (1,'Agroecología');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (1,'Agroforestería');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (1,'Agropecuaria');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (1,'Veterinaria');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (1,'Zootecnia Guarda parques');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (1,'Sistema Agroforestal');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (1,'Agricola');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (1,'Pecuaria');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (1,'Producción de Goma Nativa');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (1,'Medio Ambiente');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (2,'Carpintería Industrial');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (2,'Mecanica Industrial');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (2,'Metal Mecanica');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (2,'Fundición');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (2,'Mecatrónica');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (2,'Energías Alternativas');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (2,'Confección Textil');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (2,'Sastrería');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (2,'Tejido Industrial');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (2,'Serigrafía');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (2,'Construcción de Viviendas');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (2,'Instalaciones Sanitarias');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (2,'Instalacion de Gas Domiciliario');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (2,'Topografía');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (2,'Transformación de Alimentos');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (2,'Confección de Ropa Típica');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (2,'Electromecánica');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (2,'Construccion Civil');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (2,'Electricidad Industrial');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (2,'Encofrado');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (3,'Alfarería');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (3,'Telares Artesanales');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (3,'Bordado Artesanal');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (3,'Cestería');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (3,'Coreoplastia');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (3,'Danza');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (3,'Decoración de interiores');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (3,'Floristería');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (3,'Joyería');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (3,'Juguetería y cotillón');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (3,'Tejido Artesanal');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (3,'Marquetería');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (3,'Marroquenería');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (3,'Pintura');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (3,'Artesanía');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (3,'Talabartería');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (3,'Teatro');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (3,'Tallado de Madera');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (3,'Zapatería');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (3,'Artes musicales');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (3,'Artes gráficas');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (4,'Turismo Comunitario');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (4,'Hoteleria');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (4,'Transporte Turistico');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (4,'Gestion Turistica');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (5,'Gastronomía y Alimentación');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (5,'Belleza Integral');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (5,'Sistemas Computacionales');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (5,'Diseño Grafico');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (5,'Electricidad e Instalaciones');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (5,'Refrigeracion');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (5,'Electronica');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (5,'Electrotécnia');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (5,'Mecanica Automotriz');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (5,'Mecanica de Motocicletas');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (5,'Idioma Guaraní');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (5,'Idioma Ingles');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (5,'Idioma Quechua');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (5,'Idioma Aymara');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (5,'Mantenimiento de Celulares');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (5,'Jardineria');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (5,'Comunicador Popular');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (5,'Parvularia');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (5,'Procurador Legal de Derecho');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (5,'Sistemas Informaticos');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (5,'Ensamblaje y mantenimiento de computadoras');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (5,'Informatica Industrial');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (5,'Reposteria');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (6,'Gestión Municipal');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (6,'Marketing');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (6,'Contabilidad');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (6,'Gestión Administrativa');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (6,'Secretariado ejecutivo');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (6,'Emprendimientos Comunitarios');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (6,'Pequeña y Mediana Empresa');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (6,'Desarrollo Comunitario y Genero');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (6,'Gestion y Organización de Eventos');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (7,'Arbitraje Deportivo');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (7,'Entrenador de Práctica Deportiva');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (7,'Salud Deportiva');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (7,'Gestión Deportiva ');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (8,'Prótesis Dental');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (8,'Fisioterapia');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (8,'Medicina tradicional');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (8,'Salud Comunitaria');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (8,'Primeros Auxilios');
INSERT INTO geomaps_especialidad (area_id, especialidad) VALUES (8,'Laboratorio Clínico');