INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (1, 1, 'NO EXISTE EN CNPV 2001');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (2, 1, 'OROPEZA');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (3, 1, 'AZURDUY');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (4, 1, 'ZUDAÑEZ');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (5, 1, 'TOMINA');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (6, 1, 'HERNANDO SILES');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (7, 1, 'YAMPARAEZ');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (8, 1, 'NOR CINTI');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (9, 1, 'BELISARIO BOETO');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (10, 1, 'SUD CINTI');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (11, 1, 'LUIS CALVO');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (12, 2, 'NO EXISTE EN CNPV 2001');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (13, 2, 'MURILLO');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (14, 2, 'OMASUYOS');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (15, 2, 'PACAJES');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (16, 2, 'CAMACHO');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (17, 2, 'MUÑECAS');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (18, 2, 'LARECAJA');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (19, 2, 'FRANZ TAMAYO');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (20, 2, 'INGAVI');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (21, 2, 'LOAYZA');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (22, 2, 'INQUISIVI');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (23, 2, 'SUD YUNGAS');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (24, 2, 'LOS ANDES');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (25, 2, 'AROMA');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (26, 2, 'NOR YUNGAS');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (27, 2, 'ABEL ITURRALDE');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (28, 2, 'BAUTISTA SAAVEDRA');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (29, 2, 'MANCO KAPAC');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (30, 2, 'GUALBERTO VILLARROEL');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (31, 2, 'JOSÉ MANUEL PANDO');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (32, 2, 'CARANAVI');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (33, 3, 'NO EXISTE EN CNPV 2001');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (34, 3, 'CERCADO');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (35, 3, 'CAMPERO');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (36, 3, 'AYOPAYA');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (37, 3, 'ESTEBAN ARCE');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (38, 3, 'ARANI');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (39, 3, 'ARQUE');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (40, 3, 'CAPINOTA');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (41, 3, 'GERMAN JORDÁN');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (42, 3, 'QUILLACOLLO');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (43, 3, 'CHAPARE');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (44, 3, 'TAPACARÍ');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (45, 3, 'CARRASCO');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (46, 3, 'MIZQUE');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (47, 3, 'PUNATA');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (48, 3, 'BOLÍVAR');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (49, 3, 'TIRAQUE');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (50, 4, 'NO EXISTE EN CNPV 2001');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (51, 4, 'CERCADO');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (52, 4, 'EDUARDO AVAROA');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (53, 4, 'CARANGAS');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (54, 4, 'SAJAMA');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (55, 4, 'LITORAL DE ATACAMA');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (56, 4, 'POOPO');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (57, 4, 'PANTALEON DALENCE');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (58, 4, 'LADISLAO CABRERA');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (59, 4, 'ATAHUALLPA');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (60, 4, 'SAUCARI');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (61, 4, 'TOMAS BARRON');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (62, 4, 'SUD CARANGAS');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (63, 4, 'SAN PEDRO DE TOTORA');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (64, 4, 'SEBASTIÁN PAGADOR');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (65, 4, 'PUERTO DE MEJILLONES');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (66, 4, 'NOR CARANGAS');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (67, 5, 'NO EXISTE EN CNPV 2001');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (68, 5, 'TOMAS FRIAS');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (69, 5, 'RAFAEL BUSTILLO');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (70, 5, 'CORNELIO SAAVEDRA');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (71, 5, 'CHAYANTA');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (72, 5, 'CHARCAS');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (73, 5, 'NOR CHICHAS');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (74, 5, 'ALONSO DE IBAÑEZ');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (75, 5, 'SUR CHICHAS');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (76, 5, 'NOR LÍPEZ');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (77, 5, 'SUR LÍPEZ');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (78, 5, 'JOSÉ MARIA LINARES');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (79, 5, 'ANTONIO QUIJARRO');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (80, 5, 'BERNARDINO BILBAO RIOJA');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (81, 5, 'DANIEL CAMPOS');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (82, 5, 'MODESTO OMISTE');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (83, 5, 'ENRIQUE BALDIVIESO');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (84, 6, 'NO EXISTE EN CNPV 2001');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (85, 6, 'CERCADO');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (86, 6, 'ANICETO ARCE');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (87, 6, 'GRAN CHACO');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (88, 6, 'AVILES');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (89, 6, 'MÉNDEZ');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (90, 6, 'BURNET O'' OCONNOR');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (91, 7, 'NO EXISTE EN CNPV 2001');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (92, 7, 'ANDRÉS IBAÑEZ');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (93, 7, 'WARNES');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (94, 7, 'VELASCO');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (95, 7, 'ICHILO');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (96, 7, 'CHIQUITOS');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (97, 7, 'SARA');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (98, 7, 'CORDILLERA');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (99, 7, 'VALLEGRANDE');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (100, 7, 'FLORIDA');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (101, 7, 'OBISPO SANTIESTEVAN');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (102, 7, 'ÑUFLO DE CHÁVEZ');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (103, 7, 'ANGEL SANDOVAL');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (104, 7, 'MANUEL MARIA CABALLERO');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (105, 7, 'GERMAN BUSCH');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (106, 7, 'GUARAYOS');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (107, 8, 'NO EXISTE EN CNPV 2001');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (108, 8, 'CERCADO');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (109, 8, 'VACA DIEZ');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (110, 8, 'JOSÉ BALLIVIÁN');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (111, 8, 'YACUMA');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (112, 8, 'MOXOS');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (113, 8, 'MARBAN');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (114, 8, 'MAMORE');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (115, 8, 'ITENEZ');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (116, 9, 'NO EXISTE EN CNPV 2001');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (117, 9, 'NICOLÁS SUÁREZ');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (118, 9, 'MANURIPI');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (119, 9, 'MADRE DE DIOS');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (120, 9, 'ABUNA');
INSERT INTO `geomaps_provincia` (`id`, `departamento_id`, `provincia`) VALUES (121, 9, 'FEDERICO ROMÁN');
