INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (1, 1, 1, 'NO EXISTE EN CNPV 2001');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (2, 1, 2, 'CAPITAL (SUCRE)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (3, 1, 2, 'PRIMERA SECCIÓN (YOTALA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (4, 1, 2, 'SEGUNDA SECCIÓN (POROMA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (5, 1, 3, 'PRIMERA SECCIÓN (AZURDUY)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (6, 1, 3, 'SEGUNDA SECCIÓN (TARVITA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (7, 1, 4, 'PRIMERA SECCIÓN (ZUDAÑEZ)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (8, 1, 4, 'SEGUNDA SECCIÓN (PRESTO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (9, 1, 4, 'TERCERA SECCIÓN (MOJOCOYA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (10, 1, 4, 'CUARTA SECCIÓN (ICLA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (11, 1, 5, 'PRIMERA SECCIÓN (PADILLA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (12, 1, 5, 'SEGUNDA SECCIÓN (TOMINA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (13, 1, 5, 'TERCERA SECCIÓN (SOPACHUY)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (14, 1, 5, 'CUARTA SECCIÓN (VILLA ALCALÁ)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (15, 1, 5, 'QUINTA SECCIÓN (EL VILLAR)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (16, 1, 6, 'PRIMERA SECCIÓN (MONTEAGUDO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (17, 1, 6, 'SEGUNDA SECCIÓN (HUACARETA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (18, 1, 7, 'PRIMERA SECCIÓN (TARABUCO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (19, 1, 7, 'SEGUNDA SECCIÓN (YAMPARÁEZ)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (20, 1, 8, 'PRIMERA SECCIÓN (CAMARGO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (21, 1, 8, 'SEGUNDA SECCIÓN (SAN LUCAS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (22, 1, 8, 'TERCERA SECCIÓN (INCAHUASI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (23, 1, 9, 'PRIMERA SECCIÓN (VILLA SERRANO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (24, 1, 10, 'PRIMERA SECCIÓN (VILLA ABECIA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (25, 1, 10, 'SEGUNDA SECCIÓN (CULPINA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (26, 1, 10, 'TERCERA SECCIÓN (LAS CARRERAS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (27, 1, 11, 'PRIMERA SECCIÓN (MUYUPAMPA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (28, 1, 11, 'SEGUNDA SECCIÓN (HUACAYA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (29, 1, 11, 'TERCERA SECCIÓN (MACHARETÍ)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (30, 2, 12, 'NO EXISTE EN CNPV 2001');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (31, 2, 13, 'CAPITAL (LA PAZ)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (32, 2, 13, 'PRIMERA SECCIÓN (PALCA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (33, 2, 13, 'SEGUNDA SECCIÓN (MECAPACA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (34, 2, 13, 'TERCERA SECCIÓN (ACHOCALLA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (35, 2, 13, 'CUARTA SECCIÓN (EL ALTO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (36, 2, 14, 'PRIMERA SECCIÓN (ACHACACHI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (37, 2, 14, 'SEGUNDA SECCIÓN (ANCORAIMES)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (38, 2, 15, 'PRIMERA SECCIÓN (CORO CORO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (39, 2, 15, 'SEGUNDA SECCIÓN (CAQUIAVIRI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (40, 2, 15, 'TERCERA SECCIÓN (CALACOTO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (41, 2, 15, 'CUARTA SECCIÓN (COMANCHE)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (42, 2, 15, 'QUINTA SECCIÓN (CHARAÑA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (43, 2, 15, 'SEXTA SECCIÓN (WALDO BALLIVIAN)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (44, 2, 15, 'SEPTIMA SECCIÓN (NAZACARA DE PACAJES)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (45, 2, 15, 'OCTAVA SECCIÓN (CALLAPA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (46, 2, 16, 'PRIMERA SECCIÓN (PUERTO ACOSTA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (47, 2, 16, 'SEGUNDA SECCIÓN (MOCOMOCO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (48, 2, 16, 'TERCERA SECCIÓN (PTO. CARABUCO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (49, 2, 17, 'PRIMERA SECCIÓN (CHUMA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (50, 2, 17, 'SEGUNDA SECCIÓN (AYATA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (51, 2, 17, 'TERCERA SECCIÓN (AUCAPATA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (52, 2, 18, 'PRIMERA SECCIÓN (SORATA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (53, 2, 18, 'SEGUNDA SECCIÓN (GUANAY)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (54, 2, 18, 'TERCERA SECCIÓN (TACACOMA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (55, 2, 18, 'CUARTA SECCIÓN (QUIABAYA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (56, 2, 18, 'QUINTA SECCIÓN (COMBAYA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (57, 2, 18, 'SEXTA SECCIÓN (TIPUANI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (58, 2, 18, 'SEPTIMA SECCIÓN (MAPIRI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (59, 2, 18, 'OCTAVA SECCIÓN (TEOPONTE)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (60, 2, 19, 'PRIMERA SECCIÓN (APOLO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (61, 2, 19, 'SEGUNDA SECCIÓN (PELECHUCO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (62, 2, 20, 'PRIMERA SECCIÓN (VIACHA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (63, 2, 20, 'SEGUNDA SECCIÓN (GUAQUI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (64, 2, 20, 'TERCERA SECCIÓN (TIAHUANACU)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (65, 2, 20, 'CUARTA SECCIÓN (DESAGUADERO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (66, 2, 20, 'QUINTA SECCIÓN (SAN ANDRÉS DE MACHACA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (67, 2, 20, 'SEXTA SECCIÓN (JESÚS DE MACHACA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (68, 2, 20, 'SEPTIMA SECCIÓN (TARACO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (69, 2, 21, 'PRIMERA SECCIÓN (LURIBAY)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (70, 2, 21, 'SEGUNDA SECCIÓN (SAPAHAQUI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (71, 2, 21, 'TERCERA SECCIÓN (YACO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (72, 2, 21, 'CUARTA SECCIÓN (MALLA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (73, 2, 21, 'QUINTA SECCIÓN (CAIROMA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (74, 2, 22, 'PRIMERA SECCIÓN (INQUISIVI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (75, 2, 22, 'SEGUNDA SECCIÓN (QUIME)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (76, 2, 22, 'TERCERA SECCIÓN (CAJUATA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (77, 2, 22, 'CUARTA SECCIÓN (COLQUIRI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (78, 2, 22, 'QUINTA SECCIÓN (ICHOCA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (79, 2, 22, 'SEXTA SECCIÓN (VILLA LIBERTAD LICOMA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (80, 2, 23, 'PRIMERA SECCIÓN (CHULUMANI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (81, 2, 23, 'SEGUNDA SECCIÓN (IRUPANA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (82, 2, 23, 'TERCERA SECCIÓN (YANACACHI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (83, 2, 23, 'CUARTA SECCIÓN (PALOS BLANCOS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (84, 2, 23, 'QUINTA SECCIÓN (LA ASUNTA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (85, 2, 24, 'PRIMERA SECCIÓN (PUCARANI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (86, 2, 24, 'SEGUNDA SECCIÓN (LAJA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (87, 2, 24, 'TERCERA SECCIÓN (BATALLAS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (88, 2, 24, 'CUARTA SECCIÓN (PUERTO PÉREZ)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (89, 2, 25, 'PRIMERA SECCIÓN (SICA SICA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (90, 2, 25, 'SEGUNDA SECCIÓN (UMALA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (91, 2, 25, 'TERCERA SECCIÓN (AYO AYO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (92, 2, 25, 'CUARTA SECCIÓN (CALAMARCA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (93, 2, 25, 'QUINTA SECCIÓN (PATACAMAYA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (94, 2, 25, 'SEXTA SECCIÓN (COLQUENCHA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (95, 2, 25, 'SEPTIMA SECCIÓN (COLLANA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (96, 2, 26, 'PRIMERA SECCIÓN (COROICO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (97, 2, 26, 'SEGUNDA SECCIÓN (CORIPATA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (98, 2, 27, 'PRIMERA SECCIÓN (IXIAMAS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (99, 2, 27, 'SEGUNDA SECCIÓN (SAN BUENAVENTURA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (100, 2, 28, 'PRIMERA SECCIÓN (CHARAZANI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (101, 2, 28, 'SEGUNDA SECCIÓN (CURVA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (102, 2, 29, 'PRIMERA SECCIÓN (COPACABANA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (103, 2, 29, 'SEGUNDA SECCIÓN (SAN PEDRO DE TIQUINA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (104, 2, 29, 'TERCERA SECCIÓN (TITO YUPANQUI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (105, 2, 30, 'PRIMERA SECCIÓN (SAN PEDRO CUARAHUARA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (106, 2, 30, 'SEGUNDA SECCIÓN (PAPEL PAMPA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (107, 2, 30, 'TERCERA SECCIÓN (CHACARILLA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (108, 2, 31, 'PRIMERA SECCIÓN (SANTIAGO DE MACHACA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (109, 2, 31, 'SEGUNDA SECCIÓN (CATACORA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (110, 2, 32, 'PRIMERA SECCIÓN (CARANAVI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (111, 3, 33, 'NO EXISTE EN CNPV 2001');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (112, 3, 34, 'PRIMERA SECCIÓN (COCHABAMBA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (113, 3, 35, 'PRIMERA SECCIÓN (AIQUILE)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (114, 3, 35, 'SEGUNDA SECCIÓN (PASORAPA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (115, 3, 35, 'TERCERA SECCIÓN (OMEREQUE)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (116, 3, 36, 'PRIMERA SECCIÓN (INDEPENDENCIA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (117, 3, 36, 'SEGUNDA SECCIÓN (MOROCHATA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (118, 3, 37, 'PRIMERA SECCIÓN (TARATA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (119, 3, 37, 'SEGUNDA SECCIÓN (ANZALDO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (120, 3, 37, 'TERCERA SECCIÓN (ARBIETO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (121, 3, 37, 'CUARTA SECCIÓN (SACABAMBA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (122, 3, 38, 'PRIMERA SECCIÓN (ARANI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (123, 3, 38, 'SEGUNDA SECCIÓN (VACAS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (124, 3, 39, 'PRIMERA SECCIÓN (ARQUE)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (125, 3, 39, 'SEGUNDA SECCIÓN (TACOPAYA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (126, 3, 40, 'PRIMERA SECCIÓN (CAPINOTA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (127, 3, 40, 'SEGUNDA SECCIÓN (SANTIVAÑEZ)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (128, 3, 40, 'TERCERA SECCIÓN (SICAYA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (129, 3, 41, 'PRIMERA SECCIÓN (CLIZA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (130, 3, 41, 'SEGUNDA SECCIÓN (TOKO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (131, 3, 41, 'TERCERA SECCIÓN (TOLATA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (132, 3, 42, 'PRIMERA SECCIÓN (QUILLACOLLO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (133, 3, 42, 'SEGUNDA SECCIÓN (SIPE SIPE)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (134, 3, 42, 'TERCERA SECCIÓN (TIQUIPAYA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (135, 3, 42, 'CUARTA SECCIÓN (VINTO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (136, 3, 42, 'QUINTA SECCIÓN (COLCAPIRHUA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (137, 3, 43, 'PRIMERA SECCIÓN (SACABA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (138, 3, 43, 'SEGUNDA SECCIÓN (COLOMI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (139, 3, 43, 'TERCERA SECCIÓN (VILLA TUNARI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (140, 3, 44, 'PRIMERA SECCIÓN (TAPACARÍ)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (141, 3, 45, 'PRIMERA SECCIÓN (TOTORA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (142, 3, 45, 'SEGUNDA SECCIÓN (POJO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (143, 3, 45, 'TERCERA SECCIÓN (POCONA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (144, 3, 45, 'CUARTA SECCIÓN (CHIMORÉ)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (145, 3, 45, 'QUINTA SECCIÓN (PUERTO VILLARROEL)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (146, 3, 45, 'SEXTA SECCIÓN (ENTRE RIOS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (147, 3, 46, 'PRIMERA SECCIÓN (MIZQUE)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (148, 3, 46, 'SEGUNDA SECCIÓN (VILA VILA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (149, 3, 46, 'TERCERA SECCIÓN (ALALAY)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (150, 3, 47, 'PRIMERA SECCIÓN (PUNATA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (151, 3, 47, 'SEGUNDA SECCIÓN (VILLA RIVERO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (152, 3, 47, 'TERCERA SECCIÓN (SAN BENITO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (153, 3, 47, 'CUARTA SECCIÓN (TACACHI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (154, 3, 47, 'QUINTA SECCIÓN (CUCHUMUELA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (155, 3, 48, 'PRIMERA SECCIÓN (BOLÍVAR)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (156, 3, 49, 'PRIMERA SECCIÓN (TIRAQUE)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (157, 4, 50, 'NO EXISTE EN CNPV 2001');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (158, 4, 51, 'CAPITAL (ORURO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (159, 4, 51, 'PRIMERA SECCIÓN (CARACOLLO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (160, 4, 51, 'SEGUNDA SECCIÓN (EL CHORO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (161, 4, 51, 'TERCERA SECCIÓN (SORACACHI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (162, 4, 52, 'PRIMERA SECCIÓN (CHALLAPATA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (163, 4, 52, 'SEGUNDA SECCIÓN (QUILLACAS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (164, 4, 53, 'PRIMERA SECCIÓN (CORQUE)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (165, 4, 53, 'SEGUNDA SECCIÓN (CHOQUE COTA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (166, 4, 54, 'PRIMERA SECCIÓN (CURAHUARA DE CARANGAS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (167, 4, 54, 'SEGUNDA SECCIÓN (TURCO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (168, 4, 55, 'PRIMERA SECCIÓN (HUACHACALLA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (169, 4, 55, 'SEGUNDA SECCIÓN (ESCARA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (170, 4, 55, 'TERCERA SECCIÓN (CRUZ DE MACHACAMARCA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (171, 4, 55, 'CUARTA SECCIÓN (YUNGUYO DE LITORAL)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (172, 4, 55, 'QUINTA SECCIÓN (ESMERALDA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (173, 4, 56, 'PRIMERA SECCIÓN (POOPÓ)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (174, 4, 56, 'SEGUNDA SECCIÓN (PAZÑA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (175, 4, 56, 'TERCERA SECCIÓN (ANTEQUERA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (176, 4, 57, 'PRIMERA SECCIÓN (HUANUNI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (177, 4, 57, 'SEGUNDA SECCIÓN (MACHACAMARCA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (178, 4, 58, 'PRIMERA SECCIÓN (SALINAS DE GARCÍA MENDOZA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (179, 4, 58, 'SEGUNDA SECCIÓN (PAMPA AULLAGAS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (180, 4, 59, 'PRIMERA SECCIÓN (SABAYA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (181, 4, 59, 'SEGUNDA SECCIÓN (COIPASA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (182, 4, 59, 'TERCERA SECCIÓN (CHIPAYA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (183, 4, 60, 'PRIMERA SECCIÓN (TOLEDO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (184, 4, 61, 'PRIMERA SECCIÓN (EUCALIPTUS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (185, 4, 62, 'PRIMERA SECCIÓN (SANTIAGO DE ANDAMARCA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (186, 4, 62, 'SEGUNDA SECCIÓN (BELÉN DE ANDAMARCA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (187, 4, 63, 'PRIMERA SECCIÓN (SAN PEDRO DE TOTORA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (188, 4, 64, 'PRIMERA SECCIÓN (HUARI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (189, 4, 65, 'PRIMERA SECCIÓN (LA RIVERA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (190, 4, 65, 'SEGUNDA SECCIÓN (TODOS SANTOS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (191, 4, 65, 'TERCERA SECCIÓN (CARANGAS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (192, 4, 66, 'PRIMERA SECCIÓN (HUAYLLAMARCA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (193, 5, 67, 'NO EXISTE EN CNPV 2001');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (194, 5, 68, 'CAPITAL (POTOSÍ)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (195, 5, 68, 'PRIMERA SECCIÓN (TINGUIPAYA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (196, 5, 68, 'SEGUNDA SECCIÓN (YOCALLA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (197, 5, 68, 'TERCERA SECCIÓN (URMIRI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (198, 5, 69, 'PRIMERA SECCIÓN (UNCÍA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (199, 5, 69, 'SEGUNDA SECCIÓN (CHAYANTA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (200, 5, 69, 'TERCERA SECCIÓN (LLALLAGUA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (201, 5, 70, 'PRIMERA SECCIÓN (BETANZOS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (202, 5, 70, 'SEGUNDA SECCIÓN (CHAQUÍ)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (203, 5, 70, 'TERCERA SECCIÓN (TACOBAMBA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (204, 5, 71, 'PRIMERA SECCIÓN (COLQUECHACA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (205, 5, 71, 'SEGUNDA SECCIÓN (RAVELO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (206, 5, 71, 'TERCERA SECCIÓN (POCOATA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (207, 5, 71, 'CUARTA SECCIÓN (OCURÍ)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (208, 5, 72, 'PRIMERA SECCIÓN (S.P. DE BUENA VISTA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (209, 5, 72, 'SEGUNDA SECCIÓN (TORO TORO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (210, 5, 73, 'PRIMERA SECCIÓN (COTAGAITA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (211, 5, 73, 'SEGUNDA SECCIÓN (VITICHI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (212, 5, 74, 'PRIMERA SECCIÓN (VILLA DESACACA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (213, 5, 74, 'SEGUNDA SECCIÓN (CARIPUYO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (214, 5, 75, 'PRIMERA SECCIÓN (TUPIZA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (215, 5, 75, 'SEGUNDA SECCIÓN (ATOCHA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (216, 5, 76, 'PRIMERA SECCIÓN (COLCHA \"K\")');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (217, 5, 76, 'SEGUNDA SECCIÓN (SAN PEDRO DE QUEMES)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (218, 5, 77, 'PRIMERA SECCIÓN (SAN PABLO DE LIPEZ)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (219, 5, 77, 'SEGUNDA SECCIÓN (MOJINETE)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (220, 5, 77, 'TERCERA SECCIÓN (SAN ANTONIO DE ESMORUCO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (221, 5, 78, 'PRIMERA SECCIÓN (PUNA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (222, 5, 78, 'SEGUNDA SECCIÓN (CAIZA \"D\")');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (223, 5, 79, 'PRIMERA SECCIÓN (UYUNI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (224, 5, 79, 'SEGUNDA SECCIÓN (TOMAVE)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (225, 5, 79, 'TERCERA SECCIÓN (PORCO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (226, 5, 80, 'PRIMERA SECCIÓN (ARAMPAMPA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (227, 5, 80, 'SEGUNDA SECCIÓN (ACASIO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (228, 5, 81, 'PRIMERA SECCIÓN (LLICA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (229, 5, 81, 'SEGUNDA SECCIÓN (TAHUA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (230, 5, 82, 'PRIMERA SECCIÓN (VILLAZÓN)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (231, 5, 83, 'PRIMERA SECCIÓN (SAN AGUSTÍN)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (232, 6, 84, 'NO EXISTE EN CNPV 2001');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (233, 6, 85, 'PRIMERA SECCIÓN (TARIJA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (234, 6, 86, 'PRIMERA SECCIÓN (PADCAYA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (235, 6, 86, 'SEGUNDA SECCIÓN (BERMEJO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (236, 6, 87, 'PRIMERA SECCIÓN (YACUIBA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (237, 6, 87, 'SEGUNDA SECCIÓN (CARAPARÍ)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (238, 6, 87, 'TERCERA SECCIÓN (VILLAMONTES)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (239, 6, 88, 'PRIMERA SECCIÓN (URIONDO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (240, 6, 88, 'SEGUNDA SECCIÓN (YUNCHARÁ)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (241, 6, 89, 'PRIMERA SECCIÓN (VILLA SAN LORENZO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (242, 6, 89, 'SEGUNDA SECCIÓN (EL PUENTE)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (243, 6, 90, 'PRIMERA SECCIÓN (ENTRE RÍOS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (244, 7, 91, 'NO EXISTE EN CNPV 2001');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (245, 7, 92, 'CAPITAL (SANTA CRUZ DE LA SIERRA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (246, 7, 92, 'PRIMERA SECCIÓN (COTOCA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (247, 7, 92, 'SEGUNDA SECCIÓN (PORONGO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (248, 7, 92, 'TERCERA SECCIÓN (LA GUARDIA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (249, 7, 92, 'CUARTA SECCIÓN (EL TORNO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (250, 7, 93, 'PRIMERA SECCIÓN (WARNES)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (251, 7, 93, 'SEGUNDA SECCIÓN (OKINAWA UNO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (252, 7, 94, 'PRIMERA SECCIÓN (SAN IGNACIO DE VELASCO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (253, 7, 94, 'SEGUNDA SECCIÓN (SAN MIGUEL DE VELASCO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (254, 7, 94, 'TERCERA SECCIÓN (SAN RAFAEL)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (255, 7, 95, 'PRIMERA SECCIÓN (BUENA VISTA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (256, 7, 95, 'SEGUNDA SECCIÓN (SAN CARLOS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (257, 7, 95, 'TERCERA SECCIÓN (YAPACANÍ)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (258, 7, 95, 'CUARTA SECCIÓN (SAN JUAN)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (259, 7, 96, 'PRIMERA SECCIÓN (SAN JOSÉDE CHIQUITOS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (260, 7, 96, 'SEGUNDA SECCIÓN (PAILÓN)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (261, 7, 96, 'TERCERA SECCIÓN (ROBORÉ)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (262, 7, 97, 'PRIMERA SECCIÓN (PORTACHUELO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (263, 7, 97, 'SEGUNDA SECCIÓN (SANTA ROSA DEL SARA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (264, 7, 97, 'TERCERA SECCIÓN (COLPA BELGICA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (265, 7, 98, 'PRIMERA SECCIÓN (LAGUNILLAS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (266, 7, 98, 'SEGUNDA SECCIÓN (CHARAGUA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (267, 7, 98, 'TERCERA SECCIÓN (CABEZAS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (268, 7, 98, 'CUARTA SECCIÓN (CUEVO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (269, 7, 98, 'QUINTA SECCIÓN (GUTIÉRREZ)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (270, 7, 98, 'SEXTA SECCIÓN (CAMIRI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (271, 7, 98, 'SEPTIMA SECCIÓN (BOYUIBE)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (272, 7, 99, 'PRIMERA SECCIÓN (VALLEGRANDE)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (273, 7, 99, 'SEGUNDA SECCIÓN (TRIGAL)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (274, 7, 99, 'TERCERA SECCIÓN (MORO MORO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (275, 7, 99, 'CUARTA SECCIÓN (POSTRER VALLE)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (276, 7, 99, 'QUINTA SECCIÓN (PUCARA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (277, 7, 100, 'PRIMERA SECCIÓN (SAMAIPATA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (278, 7, 100, 'SEGUNDA SECCIÓN (PAMPA GRANDE)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (279, 7, 100, 'TERCERA SECCIÓN (MAIRANA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (280, 7, 100, 'CUARTA SECCIÓN (QUIRUSILLAS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (281, 7, 101, 'PRIMERA SECCIÓN (MONTERO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (282, 7, 101, 'SEGUNDA SECCIÓN (GRAL. SAAVEDRA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (283, 7, 101, 'TERCERA SECCIÓN (MINEROS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (284, 7, 101, 'CUARTA SECCIÓN (FERNÁNDEZ ALONSO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (285, 7, 101, 'QUINTA SECCIÓN (SAN PEDRO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (286, 7, 102, 'PRIMERA SECCIÓN (CONCEPCIÓN)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (287, 7, 102, 'SEGUNDA SECCIÓN (SAN JAVIER)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (288, 7, 102, 'TERCERA SECCIÓN (SAN RAMÓN)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (289, 7, 102, 'CUARTA SECCIÓN (SAN JULIÁN)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (290, 7, 102, 'QUINTA SECCIÓN (SAN ANTONIO DE LOMERÍO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (291, 7, 102, 'SEXTA SECCIÓN (CUATRO CAÑADAS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (292, 7, 103, 'PRIMERA SECCIÓN (SAN MATÍAS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (293, 7, 104, 'PRIMERA SECCIÓN (COMARAPA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (294, 7, 104, 'SEGUNDA SECCIÓN (SAIPINA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (295, 7, 105, 'PRIMERA SECCIÓN (PUERTO SUAREZ)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (296, 7, 105, 'SEGUNDA SECCIÓN (PUERTO QUIJARRO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (297, 7, 105, 'TERCERA SECCIÓN (CARMEN RIVERO TORREZ)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (298, 7, 106, 'PRIMERA SECCIÓN (ASCENSIÓN DE GUARAYOS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (299, 7, 106, 'SEGUNDA SECCIÓN (URUBICHÁ)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (300, 7, 106, 'TERCERA SECCIÓN (EL PUENTE)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (301, 8, 107, 'NO EXISTE EN CNPV 2001');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (302, 8, 108, 'CAPITAL (TRINIDAD)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (303, 8, 108, 'PRIMERA SECCIÓN (SAN JAVIER)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (304, 8, 109, 'PRIMERA SECCIÓN (RIBERALTA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (305, 8, 109, 'SEGUNDA SECCIÓN (GUAYARAMERÍN)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (306, 8, 110, 'PRIMERA SECCIÓN (REYES)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (307, 8, 110, 'SEGUNDA SECCIÓN (SAN BORJA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (308, 8, 110, 'TERCERA SECCIÓN (SANTA ROSA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (309, 8, 110, 'CUARTA SECCIÓN (RURRENABAQUE)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (310, 8, 111, 'PRIMERA SECCIÓN (SANTA ANA DE YACUMA )');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (311, 8, 111, 'SEGUNDA SECCIÓN (EXALTACIÓN)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (312, 8, 112, 'PRIMERA SECCIÓN (SAN IGNACIO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (313, 8, 113, 'PRIMERA SECCIÓN (LORETO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (314, 8, 113, 'SEGUNDA SECCIÓN (SAN ANDRÉS)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (315, 8, 114, 'PRIMERA SECCIÓN (SAN JOAQUÍN)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (316, 8, 114, 'SEGUNDA SECCIÓN (SAN RAMÓN)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (317, 8, 114, 'TERCERA SECCIÓN (PUERTO SILES)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (318, 8, 115, 'PRIMERA SECCIÓN (MAGDALENA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (319, 8, 115, 'SEGUNDA SECCIÓN (BAURES)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (320, 8, 115, 'TERCERA SECCIÓN (HUACARAJE)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (321, 9, 116, 'NO EXISTE EN CNPV 2001');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (322, 9, 117, 'CAPITAL (COBIJA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (323, 9, 117, 'PRIMERA SECCIÓN (PORVENIR)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (324, 9, 117, 'SEGUNDA SECCIÓN (BOLPEBRA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (325, 9, 117, 'TERCERA SECCIÓN (BELLA FLOR)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (326, 9, 118, 'PRIMERA SECCIÓN (PUERTO RICO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (327, 9, 118, 'SEGUNDA SECCIÓN (SAN PEDRO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (328, 9, 118, 'TERCERA SECCIÓN (FILADELFIA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (329, 9, 119, 'PRIMERA SECCIÓN (PUERTO GONZALES MORENO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (330, 9, 119, 'SEGUNDA SECCIÓN (SAN LORENZO)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (331, 9, 119, 'TERCERA SECCIÓN (EL SENA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (332, 9, 120, 'PRIMERA SECCIÓN (SANTA ROSA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (333, 9, 120, 'SEGUNDA SECCIÓN (INGAVI)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (334, 9, 121, 'PRIMERA SECCIÓN (NUEVA ESPERANZA)');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (335, 9, 121, 'SEGUNDA SECCIÓN (VILLA NUEVA (LOMA ALTA))');
INSERT INTO `geomaps_seccion` (`id`, `departamento_id`, `provincia_id`, `seccion`) VALUES (336, 9, 121, 'TERCERA SECCIÓN (SANTOS MERCADO)');
